jupyter-book/myst-theme

- .changeset/cuddly-camels-arrive.md
- .changeset/empty-mangos-itch.md
- .changeset/spotty-brooms-speak.md
- .changeset/witty-houses-learn.md
- packages/frontmatter/src/FrontmatterBlock.tsx
- packages/frontmatter/src/licenses.tsx
The links in JupyterLab style are blue, and the icons should be text-colored.
Fixes #28
> Improve frontmatter for Jupyter links

- packages/frontmatter/src/FrontmatterBlock.tsx
Fixes a case that may have been uncommon but is more likely when https://github.com/executablebooks/mystjs/issues/281 is done.
> empty frontmatter title should not make h1

- .changeset/brown-carpets-drop.md
- packages/jupyter/src/safe.tsx
- packages/myst-to-react/src/code.tsx
Hi, I find when we render the text with `\n` and space, it will only be considered as single space since the default html behavior. I have a quick fix. The reason we use the font-mono is we have to keep the original character width the same to copy with some formatted output like NumPy array and pandas Series. Besides, the current margin for the code blocks is too big, and I checked the directive block margin is m-4, thus it much better to change this for unified visual experience. @rowanc1 
Here is the contrast:
---------------------------------
Thanks!
> 🎨  Fix line break and space rendering and align directive margin for code blocks

- .changeset/small-kids-marry.md
- styles/jupyter.css
Now the render result is aligned with sphinx-book-theme. Looks better!
- close #47 
---------------------------------
> 🐼 Add pandas DataFrame render style

- .changeset/eleven-toes-brush.md
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/code.tsx
- packages/myst-to-react/src/links/github.tsx
- convert to xml in the renderer
> 🐛 Recognize `html` as a language

- .changeset/famous-turkeys-hunt.md
- .changeset/khaki-moles-drive.md
- packages/frontmatter/src/FrontmatterBlock.tsx
- packages/myst-to-react/src/admonitions.tsx
- packages/myst-to-react/src/code.tsx
- packages/myst-to-react/src/dropdown.tsx
- packages/myst-to-react/src/links/index.tsx
- packages/myst-to-react/src/math.tsx
- styles/block-styles.css
- styles/figures.css
- styles/grid-system.css
- styles/math.css
Originally created by @tavin in #76
This tightens up margins and simulates margin collapse in a grid by eating the top margins. This works inside and outside of the grid, while also allowing us to position child content in the margins.
Thanks @tavin for getting the ball rolling here, sorry to step on your PR. I will get this out in the next day or so as a theme-release!
> 👩🏻‍🎨 Improve margins and spacing in grids

- .changeset/chatty-vans-exist.md
- packages/myst-to-react/src/crossReference.tsx
This allows a direct cross-reference to a code block. Previously it wasn't working due to a different number of hooks being fired in react.
> 🐛 Cross references to code-blocks

- .changeset/chilled-crabs-move.md
- packages/myst-to-react/src/heading.tsx
- packages/myst-to-react/src/index.tsx
- packages/myst-to-react/src/proof.tsx
Based on `sphinx-proof`
See: https://github.com/executablebooks/mystjs/pull/384
> 👩🏽‍🏫 Initial support for proofs and theorems

- .changeset/stupid-hounds-nail.md
- packages/myst-to-react/src/heading.tsx
This fixes jupyterlab, which overrides the text color for links, and it makes the hash-links a inherited color (rather than blue).
> 🐛 Text color label for proof

- .changeset/lovely-onions-explain.md
- packages/myst-to-react/src/cite.tsx
Another casualty of #97.
See:
- https://github.com/executablebooks/jupyterlab-myst/issues/127
> 🐛 Fix hooks in citation

- .changeset/eight-buckets-whisper.md
- packages/site/src/loaders/utils.ts
This brings back footer links when there is only a single project.
> 🐛 Footer links in single project mode

- .changeset/friendly-cooks-dream.md
- packages/jupyter/src/providers.tsx
this caused a runtime error in notebook processing from mdast
> 🛠 fix for empty blocks in notebooks

- package-lock.json
- packages/jupyter/package.json
- packages/site/package.json
- packages/site/src/pages/Root.tsx
This should fix https://github.com/executablebooks/mystjs/issues/441 by using the correct `BASE_URL`.
I could not get a local static build or manual deployment to gh-pages working (the [docs](https://mystmd.org/guide/deployment#deploying-to-github-pages) could be clearer about where to set the env var in the non-action local build case... locally? or in an env var on github?)
> ⛺️ `thebe` async loading uses `BASE_URL`

- packages/jupyter/src/controls/NotebookToolbar.tsx
- packages/jupyter/src/embed.tsx
- packages/jupyter/src/index.tsx
- packages/jupyter/src/output.tsx
- packages/site/src/components/Navigation/Navigation.tsx
- packages/site/src/components/Navigation/TableOfContents.tsx
- packages/site/src/components/Navigation/TopNav.tsx
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/Root.tsx
- styles/block-styles.css
- styles/hover.css
- styles/typography.css
This moves the in-article controls to the top of the embed node and also fixes the z-index issues we talked about in #140. I have also removed the article notebook toolbar, I think we could bring it back, but I didn't really think it was necessary? Linked notebooks still work together!
> 🕹 Move controls to embed node

- themes/article/.gitignore
- themes/article/app/root.tsx
- themes/article/app/routes/$slug.tsx
- themes/article/package.json
@stevejpurves, some of the changes made meant that various things were breaking if we don't enable thebe. I think that is probably fine, but it would be nicer if it was a bit more lenient on the providers. The `BusyScope` provider just errors out. I think this was me bringing it into the import rather than in explicitly added controls.
This is a bit of a hacky job to make the article-theme work again, I think we can go back and refactor some of this down.
> 🐛 Enable thebe on `article-theme`

- .changeset/fuzzy-beans-study.md
- packages/jupyter/src/BinderBadge.tsx
- packages/jupyter/src/embed.tsx
- packages/jupyter/src/execute/hooks.ts
- packages/jupyter/src/execute/provider.tsx
- packages/jupyter/src/providers.tsx
- packages/site/src/pages/Article.tsx
addresses #148 and https://github.com/executablebooks/mystmd/issues/461 with some concession to minimally altering the narritive/reading experience, while still keeping a reference link to the source notebook when thebe is not activated.
> 🔭 compute controls no longer shown when thebe not enabled

- .changeset/lemon-penguins-draw.md
- themes/article/app/routes/$slug.tsx
- themes/article/template.yml
Adds options making the article an even more single page experience by removing the TOC and footer navigations.
> ⌥ adding `hide_footer` and wiring up `hide_toc` in article theme

- styles/jupyter.css
This is minimum viable theme improvements for using thebe in dark mode. I think it does belong here rather than in Thebe? But maybe not @stevejpurves?
> 🪐☀️ Dark mode for Jupyter widgets

- .changeset/itchy-dogs-join.md
- packages/jupyter/src/output.tsx
This change should immediately allow some outputs to be scrollable (e.g. plain text rendered as pre), in combination with [this change in thebe](https://github.com/executablebooks/thebe/pull/662) it should also allow output contents like wide pandas tables to scroll again.
> 📜 enable x-scrolling at figure level

- .changeset/clever-carrots-fix.md
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/code.tsx
- packages/myst-to-react/src/components/CopyIcon.tsx
- packages/myst-to-react/src/heading.tsx
This adds a few improvements for accessibility when focused.
> 👩‍💻 Simplifications to the code-copy button

- themes/article/template.yml
- themes/book/template.yml
MyST templates changed how they download site themes (download/unzip instead of clone). This means we need to explicitly list required files. However! That's pretty easy because glob patters are now supported.
Corresponding mystjs pr: https://github.com/executablebooks/mystmd/pull/494
> 🗂 Add files to theme's template.yml files

- .changeset/beige-mice-attend.md
- packages/jupyter/src/output.tsx
When an embedded notebook cell cell had no outputs it was deemed as "safe" and placehodlers were not being rendered.
> 🏞 Fix placeholders when outputs are empty

- .changeset/funny-turtles-tease.md
- packages/site/src/components/DocumentOutline.tsx
Abbreviations in a title would show up in the outline, which we don't want. We do want math showing up, so the copycode is HTML focused.
> 🔌 Remove `abbr` elements from document outline

- .changeset/spotty-insects-jam.md
- packages/frontmatter/src/FrontmatterBlock.tsx
This hides the badges bar in frontmatter if various elements are not defined.
> 🐛 Hide frontmatter bar properly

- .changeset/bright-lobsters-draw.md
- packages/frontmatter/src/FrontmatterBlock.tsx
Closes none.
This PR allows adding an author's Twitter account next to their ORCID and email.
The Twitter account has to be added to the author's list in `index.md` for the book theme or `myst.yml` for the article theme. Here's an example:
```yaml
authors:
- name: Eneko Uruñuela
affiliations:
- Basque Center on Cognition, Brain and Language, Donostia - San Sebastián, Spain
- University of the Basque Country (EHU/UPV), Donostia-San Sebastián, Spain
orcid: 0000-0001-6849-9088
email: e.urunuela@bcbl.eu
twitter: eurunuela
```
> 🐦  Show author's Twitter account next to ORCID and email

- .changeset/calm-socks-learn.md
- .changeset/eleven-pugs-cover.md
- .changeset/flat-spoons-cheat.md
- .changeset/friendly-flowers-push.md
- packages/site/src/components/DocumentOutline.tsx
- packages/site/src/components/Headers.tsx
- packages/site/src/components/Navigation/TableOfContents.tsx
- packages/site/src/components/index.ts
- themes/article/app/routes/$.tsx
- Remove the minimum height from the banner
- Allow document outline to have children
- Add supporting documents export from MyST Site
- Change height calculation for `useOutlineHeight` for container offset
> 🎑 General theme improvements for Article Theme

- .changeset/quick-apes-crash.md
- packages/frontmatter/src/Authors.tsx
- packages/frontmatter/src/FrontmatterBlock.tsx
- packages/frontmatter/src/downloads.tsx
- packages/frontmatter/src/licenses.tsx
- packages/jupyter/src/controls/Buttons.tsx
- packages/jupyter/src/controls/Spinner.tsx
- packages/jupyter/src/decoration.tsx
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/admonitions.tsx
- packages/myst-to-react/src/components/CopyIcon.tsx
- packages/myst-to-react/src/components/LinkCard.tsx
- packages/myst-to-react/src/dropdown.tsx
- packages/myst-to-react/src/exercise.tsx
- packages/myst-to-react/src/inlineError.tsx
- packages/myst-to-react/src/links/github.tsx
- packages/myst-to-react/src/links/index.tsx
- packages/myst-to-react/src/links/wiki.tsx
- packages/myst-to-react/src/math.tsx
- packages/myst-to-react/src/proof.tsx
- packages/site/src/components/DocumentOutline.tsx
- packages/site/src/components/FooterLinksBlock.tsx
- packages/site/src/components/Navigation/TopNav.tsx
- themes/article/app/routes/$.tsx
This should be a no-op for the most part. However, when styles fail to load the experience is significantly better:
Before it was a giant icon as the first thing that you see.
> 🎨 Update icon sizes to be explicit

- .changeset/mean-weeks-drop.md
- .changeset/stupid-cobras-flash.md
- packages/jupyter/src/decoration.tsx
- packages/providers/src/theme.tsx
- packages/site/src/components/DocumentOutline.tsx
- packages/site/src/components/Headers.tsx
- packages/site/src/components/Navigation/Navigation.tsx
- packages/site/src/components/Navigation/TableOfContents.tsx
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/Root.tsx
- themes/article/app/root.tsx
- themes/article/app/routes/$.tsx
- themes/article/app/routes/_index.tsx
- themes/book/app/root.tsx
- themes/book/app/routes/$.tsx
This allows the top to be used throughout the app, e.g. sticky controls in Jupyter.
A new provider `useThemeTop` is supported that can be controlled through the Document or Theme components.
> 🎩 Article top improvements

- .changeset/giant-owls-matter.md
- packages/site/src/components/Navigation/TableOfContents.tsx
The reordering in some of the accessibility changes required a z-index fix for pages with navigation content.
cc @stevejpurves
> 🐛 Navigation clicking in book theme

- .changeset/silver-bananas-kiss.md
- packages/myst-to-react/src/cite.tsx
- styles/citations.css
This allows citations in a group to be more than a `cite` html element.
> 🎨 Update citation styles

- .changeset/cold-pumpkins-wave.md
- packages/frontmatter/src/FrontmatterBlock.tsx
- packages/myst-to-react/src/heading.tsx
- packages/myst-to-react/src/index.tsx
- packages/site/src/components/Abstract.tsx
- packages/site/src/components/SkipToArticle.tsx
- packages/site/src/components/index.ts
- packages/site/src/pages/Article.tsx
- themes/article/app/root.tsx
- themes/article/app/routes/$.tsx
- themes/book/app/root.tsx
Addresses #231 
This can still be improved a lot but fulfills the basic need, a keyboard focus jumps ahead of nav and frontmatter.
There are some remaining issues:
* all themes - the page does not scroll as desired on use of the links on first page load, maybe fighting with other scroll restore behaviour?
* article theme - skip to supporting documents would be a good addition
> ⌨️ Skip-to-content keyboard accessibility

- .changeset/four-seas-wink.md
- packages/myst-to-react/src/cite.tsx
- packages/myst-to-react/src/crossReference.tsx
- packages/myst-to-react/src/footnotes.tsx
- packages/myst-to-react/src/links/github.tsx
- packages/myst-to-react/src/links/rrid.tsx
- styles/hover.css
This gets around the following error:
> 🕴 Hover CSS improvement for Remix v2

- .changeset/warm-mice-repair.md
- packages/jupyter/src/controls/Buttons.tsx
- packages/jupyter/src/hooks.ts
- packages/jupyter/src/index.tsx
- packages/jupyter/src/providers.tsx
This enables building of components with different UI/UX needs whilst still reusing most of the underlying logic for the "Launch Binder" button.
> 🪝move launch binder logic to reusable hook

- .changeset/plenty-bears-applaud.md
- packages/myst-to-react/src/basic.tsx
- packages/myst-to-react/src/links/index.tsx
The zero-width space is used for formatting.
This is now turned into a `<wbr>` tag, which doesn't copy to clipboard.
> 🔗 Link copy should not include zero-width space

- .changeset/stupid-socks-report.md
- packages/site/src/pages/Article.tsx
- themes/article/app/routes/$.tsx
- themes/book/app/routes/$.tsx
I'm not sure how `design` is coming into article frontmatter, so I'm not sure if these changes are correct. However, with the introduction of `siteConfig.options`, `siteConfig.design` is now moved to `siteConfig.options.design`...
> 👩‍🎨 Nest design under options

- packages/jupyter/src/ConnectionStatusTray.tsx
- packages/jupyter/src/execute/provider.tsx
- packages/jupyter/src/providers.tsx
- packages/site/src/pages/Article.tsx
- themes/article/app/routes/$.tsx
👍 canCompute now returns false on falsy `thebe|jupyter` key
Fixes #255
> 💻  Notebook toolbar always on but not functional

- .changeset/four-forks-begin.md
- packages/jupyter/src/execute/provider.tsx
This led to sources being undefined and `keys` being mapped incorrectly.
> 🌳 correctly select figures with outputs and get figure node

- package-lock.json
- packages/site/package.json
- packages/site/src/components/Navigation/TableOfContents.tsx
- packages/site/src/components/Navigation/TableOfContentsItems.tsx
- styles/app.css
- styles/toc.css
See https://github.com/executablebooks/mystmd/issues/478
> 🪆 Improve Table of Contents

- .changeset/clean-ears-allow.md
- .changeset/little-trains-beam.md
- .changeset/stupid-socks-report.md
- packages/common/src/utils.ts
- packages/site/src/components/ContentBlocks.tsx
- packages/site/src/components/Navigation/TopNav.tsx
- packages/site/src/pages/Article.tsx
- themes/article/app/routes/$.tsx
- themes/book/app/routes/$.tsx
`block` nodes have a "visibility" attribute that is getting more use with this PR: https://github.com/executablebooks/mystmd/pull/736  - parts defined in frontmatter are moved to hidden content blocks. This PR respects that flag by simply not rendering the block content.
> 🧱 Respect `visibility: remove` on blocks

- .changeset/nasty-carrots-attack.md
- packages/jupyter/src/execute/index.ts
- packages/jupyter/src/execute/utils.ts
- packages/site/src/components/ContentBlocks.tsx
This PR consolidates the logic for finding `code`/`output` cells in a `block`. It also reduces the strictness of this logic:
Previously the only block structure that resolved to executable code/output was:
```
block
|- code
|- output
```
Now, that structure is still allowed along with:
```
block
|- figure
|- code
|- output
|- caption
```
as added in https://github.com/executablebooks/mystmd/pull/760
> 📒 Allow executable code/output to be inside a figure

- .changeset/neat-spiders-chew.md
- packages/site/src/components/DocumentOutline.tsx
- themes/book/app/routes/$.tsx
- themes/book/template.yml
See executablebooks/mystmd#773
> 🗺 Add option for `maxdepth` on an outline

- .changeset/angry-wolves-obey.md
- .changeset/six-trees-rule.md
- .changeset/twenty-hounds-smile.md
- package-lock.json
- packages/jupyter/package.json
- packages/jupyter/src/controls/ArticleCellControls.tsx
- packages/jupyter/src/controls/Buttons.tsx
- packages/jupyter/src/controls/NotebookToolbar.tsx
- packages/jupyter/src/execute/leaf.tsx
- packages/jupyter/src/execute/provider.tsx
- packages/jupyter/src/hooks.ts
- packages/jupyter/src/providers.tsx
- packages/providers/src/index.tsx
- packages/providers/src/project.tsx
- packages/site/package.json
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/Root.tsx
- themes/article/.gitignore
- themes/article/app/routes/$.tsx
- themes/book/.gitignore
Prior to this change, it was not possible to completely override `thebe` options if there was no `thebe|jupyter` field set in the frontmatter at all.
This remedies that and gives much more flexbility to consumers.
> 🗿always apply overrides and allow for `undefined` options

- .changeset/yellow-flies-attack.md
- packages/jupyter/src/ConnectionStatusTray.tsx
- packages/jupyter/src/ErrorTray.tsx
- packages/jupyter/src/decoration.tsx
- packages/jupyter/src/execute/hooks.ts
- packages/jupyter/src/execute/provider.tsx
- packages/jupyter/src/providers.tsx
- packages/jupyter/src/utils.ts
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/Root.tsx
- themes/article/app/root.tsx
- themes/article/app/routes/$.tsx
- themes/book/app/root.tsx
Bundling the ThebeOptions provider in beside the ThebeServer really hurts flexiblity. The ThebeOptions could be much further up the render tree and early analysis of the thebe option can be used to setup the site, e.g. like knowing whether to load thebe lite or not.
Providers are split out here and we also add flags to enable different parts of the compute ui separately.
> 🕺split out compute options provider and add feature flags

- packages/jupyter/src/BinderBadge.tsx
- packages/jupyter/src/ConnectionStatusTray.tsx
- packages/jupyter/src/controls/Buttons.tsx
Launch Binder doesn't click with many readers, where Launch Jupyter does.
> 📇 swaping binder for jupyter in ui

- .changeset/healthy-dragons-report.md
- packages/common/src/utils.ts
- themes/article/app/root.tsx
- themes/book/app/root.tsx
`twitter` is a site option for book/article theme in the `template.yml`. However, the themes were not picking this up from the correct place. Now, for meta tags, twitter comes from options.
> 🐥 Support twitter as site option

- .changeset/smooth-yaks-talk.md
- packages/myst-to-react/src/image.tsx
This fixes when videos work locally, but may not work if the URL is changed by adding a query string.
> 🐛 Videos do not show if the URL contains queries

- packages/jupyter/src/convertImages.ts
This fixes https://github.com/executablebooks/mystmd/issues/916 in local testing
`image/svg-xml` is the correct and offical (IANA) mimetype identifier for SVG images, so we should be filtering based on that. 
`image/svg` is not an official mimetype at all, but I've left it in place - hesistating here in case the original code was covering some edge case that's out there ins the wild.
Happy to remove it though if that's the concensus.
> 🔧 added official mimetype for svg when filtering output bundles

- package-lock.json
- packages/jupyter/package.json
- packages/jupyter/src/execute/leaf.tsx
- packages/jupyter/src/globals.d.ts
- packages/jupyter/src/jupyter.tsx
- packages/jupyter/src/plotly.ts
- patches/jupyterlab-plotly+5.18.0.patch
Plotly plots are not working in `myst-theme` as the rendermime factory is not being registered.
Recent changes to plotly (as compared to pre-juptyerlab 4 extensions) make it more tricky to bring in the plotly js renderer from the extension package.
For anything more than a short term fix here we need to move the myst-theme towards making proper use of the jupyterlab extension mechanism via federated modules, so that we can configure in myst/environment which extensions to load and have those included in the website build appropriately. As discussed with @agoose77 @rowanc1 
As a short term solution, this PR makes a small patch to the plotly jupyterlab extension module in order to load this dynamically.
In passive mode, the module is only loaded when a plotly mimetype is seen in an …
> interim support for plotly

- .changeset/forty-dogs-march.md
- packages/myst-to-react/src/basic.tsx
Hey @fwkoch, I pinged you for review of this because I need to be better at pinging "not rowan"! Let me know if I should instead ask Rowan for review on this!
This PR simply passes through the `align` attribute of `TableCell` to the underlying `td`/`th` element.
As a PR in myst-theme, this doesn't address the problem of alignment in HTML / LaTeX exports.
> feat: support the align attribute in tablecell

- .changeset/shy-buses-sit.md
- packages/jupyter/src/execute/leaf.tsx
- packages/jupyter/src/plotly.ts
Recent changes to plotly introduced a problem for noteobok based pages at execution time, this PR fixes that ensuring that plotly is loaded before the notebook is deemed built. This is due to the fact that we expect a rendermime registry to be constructed during the notebook build phase, which in turn needs to wait on plotly.
fixes #322
> 🛠 fix notebook build process

- .changeset/odd-cycles-build.md
- packages/myst-to-react/src/basic.tsx
- styles/figures.css
- styles/index.js
I'm not sure if this is best-practice; I'm implying that a pull-quote really is a container-level feature rather than a blockquote-level feature. That follows from how they're implemented in https://github.com/executablebooks/mystmd/pull/961
> 💬 Add style for pull-quotes

- packages/myst-to-react/src/basic.tsx
This PR is the sibling to executablebooks/mystmd#989, which adds a new `kbd`/`keyboard` role to MyST.
> ⌨️ Add `keyboard` renderer

- .changeset/modern-weeks-repeat.md
- .changeset/ninety-planes-pump.md
- packages/common/src/utils.ts
- packages/site/src/seo/meta.ts
- themes/article/app/root.tsx
- themes/article/app/routes/$.tsx
- themes/article/app/routes/_index.tsx
- themes/article/remix.config.dev.js
- themes/article/remix.config.prod.js
- themes/book/app/root.tsx
- themes/book/app/routes/$.tsx
- themes/book/app/routes/_index.tsx
- themes/book/remix.config.dev.js
- themes/book/remix.config.prod.js
In executablebooks/myst-theme#332, @choldgraf observed that opengraph metadata is missing from the static MyST sites. It turns out it's also missing from the dynamic routes too.
I believe the root cause is fixed by this PR, though I have not tested the static export!
Fixes executablebooks/myst-theme#332
> 🏷 Pull frontmatter from proper key

- .changeset/seven-hornets-double.md
- packages/myst-to-react/src/aside.tsx
- packages/myst-to-react/src/basic.tsx
- packages/myst-to-react/src/index.tsx
See executablebooks/mystmd#1132
> 💅 🖼️ Add topic directive

- .changeset/giant-bugs-rest.md
- packages/jupyter/src/decoration.tsx
- packages/jupyter/src/embed.tsx
- packages/jupyter/src/figure.tsx
This PR prevents enabling the thebe power button on nodes where source `location` file is not available (e.g. externally cross-referenced figures)
> 🧮 Require location on node source to enable jupyter computation

- .changeset/kind-months-drive.md
- packages/myst-to-react/src/crossReference.tsx
The 3-node default for `selectMdastNodes` was removed when pulling that function up to `myst-common`. This restores the limit here so we do not get overly long popups.
> 🥉 Keep 3 node default for xref popup

- .changeset/proud-waves-mix.md
- packages/myst-to-react/src/crossReference.tsx
To reproduce this bug you need a MyST site with a cross reference to a second site that contains a cross reference to a third site. The theme will try to access the third site's content at the second site's base url.
You can recreate this with: `[](xref:mystmd#tbl:syntax-xref)`
This PR simply changes the order of base url resolution to prioritize the node's `remoteBaseUrl`, if defined, over the parent's `remoteBaseUrl`.
> 🥤 Use correct remoteBaseUrl on nested cross reference popups

- .changeset/stale-camels-count.md
- packages/site/src/components/Backmatter.tsx
This also removes unnecessary `div`s from the part rendering.
> 🔑 Fix react keys error message for backmatter parts

- .changeset/four-tips-swim.md
- packages/myst-to-react/src/basic.tsx
- packages/myst-to-react/src/crossReference.tsx
- packages/myst-to-react/src/exercise.tsx
- packages/myst-to-react/src/footnotes.tsx
- packages/myst-to-react/src/hashLink.tsx
- packages/myst-to-react/src/heading.tsx
- packages/myst-to-react/src/index.tsx
- packages/myst-to-react/src/math.tsx
- packages/myst-to-react/src/proof.tsx
- packages/site/src/components/Footnotes.tsx
- packages/site/src/components/index.ts
- styles/app.css
- styles/backmatter.css
- themes/article/app/components/Article.tsx
- themes/book/app/components/ArticlePage.tsx
See: executablebooks/mystmd#926
Can click on the footnotes back and forward to go from the bottom of the page to the reference. Hover still works. I have refactored some of the scroll logic to enable us to do push state rather than replace in the future, however that didn't work in my first pass, leaving that for another iteration!
> 🦶🎵 Add footnotes to bottom of page

- .changeset/nasty-hotels-burn.md
- styles/index.js
This adds CSS styles for h4/h5/h6 so that they look like headers in the text.
It also consolidates one CSS rule, mostly so that I can validate with @stevejpurves that this JS-based configuration lets us write the same kind of structures that work in SCSS/SASS. Is that right Steve?
- closes #389
> 🎨 Add H5 and H6 styles

- .changeset/hot-papayas-end.md
- styles/backmatter.css
- styles/block-styles.css
- styles/cross-references.css
- styles/grid-system.css
- styles/tasklists.css
This fixes a style bug where the link styles get overridden by recent back-matter changes.
We only need to include the following once:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
> 🐛 Styles overridden

- .changeset/itchy-ads-cover.md
- packages/myst-to-react/src/aside.tsx
- packages/myst-to-react/src/code.tsx
- packages/myst-to-react/src/iframe.tsx
- packages/myst-to-react/src/image.tsx
Motivation for this PR is to enable more control over final rendering of some container directives by allowing authors to use the `class` option to add classes to the final container component that is rendered on page. 
When teamed with user defined stylesheets this will be very powerful in the core themes and is immediately useful when using current/known tailwind classes, and in custom themes.
tested with:
```
this is the main content this is more main content this is more main content this is more main content this is more main content this is more main content this is more main content
:::{aside}
:class: test-aside
this is an aside this is an aside this is an aside this is an aside this is an aside this is an aside this is an aside
:::
this is more main content this is more main …
```
> 🪈 propagate `class` value through to react on container type directives

- .changeset/gold-doors-mix.md
- packages/site/src/components/Abstract.tsx
- packages/site/src/components/Backmatter.tsx
- packages/site/src/components/ContentBlocks.tsx
- packages/site/src/components/DocumentOutline.tsx
- packages/site/src/components/FooterLinksBlock.tsx
- packages/site/src/components/FrontmatterParts.tsx
- packages/site/src/components/Keywords.tsx
- packages/site/src/components/Navigation/ActionMenu.tsx
- packages/site/src/components/Navigation/HomeLink.tsx
- packages/site/src/components/Navigation/Loading.tsx
- packages/site/src/components/Navigation/TopNav.tsx
- packages/site/src/components/Navigation/index.tsx
- packages/site/src/components/index.ts
- packages/site/src/pages/Article.tsx
- packages/site/src/seo/meta.ts
- packages/site/src/utils.ts
This PR aims to export as many re-usable components and hooks that `@myst-theme/site` has to offer in order to make it easier to create new themes that still lean on the components offered by that package.
> 🚢 exporting additional components and hooks

- .changeset/tidy-dragons-battle.md
- packages/site/src/components/SkipToArticle.tsx
- themes/article/app/root.tsx
- themes/book/app/root.tsx
This adds a configurable `SkipTo` component, whilst deprecating `SkipToArticle`. This makes for more sensible usage in the core myst themes (e.g. no `frontmatter={false}`) as well as enabling consistent but customisable skip to links in custom and user themes
> ⏭️ add `SkipTo` and use it in themes

- .changeset/hot-glasses-march.md
- packages/site/src/components/Abstract.tsx
- packages/site/src/components/Backmatter.tsx
- packages/site/src/components/Bibliography.tsx
- packages/site/src/components/Footnotes.tsx
- packages/site/src/components/FrontmatterParts.tsx
- packages/site/src/components/Keywords.tsx
Some of the container components for (XxxParts, Footnotes, Bibliography) did not allow for precise assignment of grid and `col-*` classes, meaning that although they work fine in `article-grid` with the default layouts in the core `themes` they behave unexpectedly when trying to position them in different columns and especially with the new `article-center-grid`.
Adding these className parameters allows for significant control in grid positioning, as is already the case with ContentBlocks.
> 💉 adding className props

- .changeset/kind-glasses-fix.md
- packages/frontmatter/src/FrontmatterBlock.tsx
This adds a tooltip for the Jupyter Notebook icon in the headers.
> :mag: Add title for Jupyter Notebook badge

- .changeset/four-pandas-confess.md
- packages/myst-to-react/src/basic.tsx
This small change should allow us to use cross-references to target spans/divs.
> 🪪 Add id to span and div nodes

- .changeset/forty-panthers-cheer.md
- packages/site/src/components/Navigation/TopNav.tsx
- themes/article/app/types.ts
- themes/book/app/routes/$.tsx
> :hamburger: Remove TOC hamburger icon when TOC itself is hidden

- .changeset/new-bags-dance.md
- packages/frontmatter/src/FrontmatterBlock.tsx
This PR is the counterpart to https://github.com/jupyter-book/mystmd/pull/1426 which ensures that the validated frontmatter contains `yyyy-mm-dd` formatted dates as wall-clock dates (i.e. not tied to a timezone).
At the moment, myst-theme incorrectly builds a UTC object, such that the result is TZ sensitive. This PR fixes the date handling such that we're not displaying dates in any timezone; what you put in is what you put out.
> 📅 Fix representation of MyST date strings

- .changeset/many-lemons-worry.md
- package-lock.json
- packages/jupyter/package.json
- packages/site/package.json
`thebe` introduced a breaking API change in the latest patch releases 🫠 `0.4.8`,`.0.4.9` which is causing `thebe` to fail in downstream themes and will break releases here if the lock is removed.
The `myst-theme` changes needed to consume those new APIs are actually in #426 #429 so independently bumping versions and adjusting code here seems counter productive. So this PR is intended as a stopgap until that widget hydration work can come in.
> 📌 `thebe` deps

- .changeset/blue-melons-sin.md
- package-lock.json
- packages/site/package.json
`@myst-theme/site` has 2.0 peer deps for remix, which is premature and causing downstream problems. Also we should be pointing to 1.19 not 1.17.
> 📦🔒 fixing peer deps

- .changeset/early-bottles-cheat.md
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/ErrorUnhandled.tsx
- packages/site/src/pages/Root.tsx
- packages/site/src/pages/index.ts
- packages/site/src/seo/meta.ts
- themes/article/app/root.tsx
- themes/article/app/routes/$.tsx
- themes/article/app/routes/_index.tsx
- themes/article/remix.config.dev.js
- themes/article/remix.config.prod.js
- themes/book/app/root.tsx
- themes/book/app/routes/$.tsx
- themes/book/app/routes/_index.tsx
- themes/book/remix.config.dev.js
- themes/book/remix.config.prod.js
More work on preparing for v2 in Remix, fixing `CatchBoundary` and some other small changes.
> :gear: More preparation for Remix v2 (1)

- .changeset/tidy-candles-develop.md
- packages/jupyter/src/figure.tsx
- packages/myst-to-react/src/MyST.tsx
- packages/myst-to-react/src/index.tsx
- packages/myst-to-react/src/links/index.tsx
- packages/providers/package.json
- packages/providers/src/index.tsx
- packages/providers/src/renderers.spec.tsx
- packages/providers/src/renderers.tsx
- packages/providers/src/theme.tsx
- packages/providers/src/types.ts
- packages/site/src/components/renderers.ts
- packages/site/src/pages/Root.tsx
This allows for multiple renderers to be attached to a single node, based on a match of the kind.
For example you can now add a specific renderer for a `link[kind=github]`. This allows for inheriting these renderers and then extending or overriding them independently.
> ⏩ Extend renderers to allow for kind/subtypes

- .changeset/cyan-taxis-help.md
- packages/providers/src/ui.tsx
- packages/site/src/components/Navigation/PrimarySidebar.tsx
- themes/book/app/routes/$.tsx
Presently, the TOC is always trimmed to the page length, in full-width OR narrow displays:
- Wide:   
- Narrow  
This PR tweaks the computation to detect when the "wide" media query is true/false:
- Wide:  
- Narrow:  
I think there might be some overflow problems, but I don't *think* they're caused by this PR.
> 📏 Allow full-length TOC when sidebar is useable

- .changeset/nice-suns-crash.md
- README.md
- themes/article/app/components/ArticlePageAndNavigation.tsx
- themes/article/app/utils/loaders.server.ts
- themes/book/app/utils/loaders.server.ts
Fixes #342.
* Regarding #466, simply adds the `ThemeButton` to the article theme. Tested locally:
* Enables setting `CONTENT_CDN`  through env to replace `localhost:{port}` with `https://remote.example.com`. 
> [!NOTE]
> Right before opening this PR, I realized that a similar PR #346 exists, enabling `{hostname}:{port}`. This is slightly different as the purpose is to connect to a remote CDN host (tested with `https://cdn.neurolibre.org`) without specifying a port. Happy to account for the changes from #346 to avoid conflict.
> Remote CDN and theme button for the article theme

- .changeset/tame-tips-rush.md
- themes/article/app/components/ArticlePage.tsx
- themes/book/app/components/ArticlePage.tsx
- themes/book/app/routes/$.tsx
See https://github.com/jupyter-book/mystmd/pull/1536
> 💽 Add site options to each page

- .changeset/modern-steaks-destroy.md
- packages/site/src/components/DocumentOutline.tsx
- packages/site/src/components/SkipToArticle.tsx
This changes the focus to the element, rather than just scrolling to it.
> 🎹 Improve keyboard accessibility

- .changeset/itchy-doors-leave.md
- packages/common/src/types.ts
- packages/common/src/utils.ts
- packages/frontmatter/src/FrontmatterBlock.tsx
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/crossReference.tsx
- packages/providers/src/references.tsx
- packages/site/src/pages/Article.tsx
- packages/site/src/pages/ErrorUnhandled.tsx
- packages/site/src/utils.ts
- themes/article/app/components/Article.tsx
- themes/book/app/components/ArticlePage.tsx
This consumes the updates to frontmatter parts introduced in MyST here: https://github.com/jupyter-book/mystmd/pull/1586
Now, the theme may look in page `frontmatter.parts` for additional parts trees. Hopefully this will simplify consuming other custom parts, besides the baked-in "abstract," "acknowledgments," etc.
> 🏗 Support parts mdast trees in page frontmatter

- .changeset/light-donkeys-explode.md
- package-lock.json
- package.json
- packages/site/src/components/DocumentOutline.tsx
- themes/article/app/utils/loaders.server.ts
Most of the URL folder structure changes were landed in https://github.com/jupyter-book/myst-theme/pull/489
This just adds `slugToUrl` in a couple places that were missed.
> 🗂 Update slugToUrl in article theme

- .changeset/purple-bugs-relate.md
- packages/site/src/components/Navigation/Search.tsx
Fixes #478, and hides the `... ` / ` ...` elements from the rendered text (use CSS instead).
> 📏 Replace token-limit with char-limit in search listings

- .changeset/tidy-ducks-breathe.md
- packages/diagrams/src/index.tsx
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/basic.tsx
- packages/myst-to-react/src/dropdown.tsx
This PR should increase the number of directives that support `class` and `identifier` in rendering. I doubt I've got them all, but I created a test case from the directives list: https://mystmd.org/guide/directives
<details><summary>Details</summary>
````markdown
:::{aside} An Optional Title
:class: red
This is an aside. It is not entirely relevant to the main article.
:::
:::{tip}
:class: red
Try changing `tip` to `warning`!
:::
:::{bibliography}
:class: red
:::
:::{blockquote}
:name: quote
:class: red
Hello
-- world
:::
:::{code} python
:class: red
x + y
:::
:::{div}
:class: red
div
:::
:::{dropdown}
:class: red
dropdown
:::
:::{embed} #quote
:class: red
:::
:::{figure} https://picsum.photos/512
:class: red
:::
:::{glossary}
:class: red
Foo
: Bar
:::
:::{iframe} https://google.com …
```
> 🪄 Add more `class` support to directives

- .changeset/new-students-brush.md
- packages/jupyter/src/execute/leaf.tsx
Users with `.md` files that contain kernelspecs currently report that the `cwd` of running kernels in Thebe (via the power-button UX) is incorrect.
Digging into this, Thebe assumes that we have an `ipynb` file when performing filepath substitution during session provisioning. This means that the `cwd` is incorrect for `.md` files.
This PR relaxes the extension check, and introduces a maybe-incorrect `.ipynb` extension because it's ultimately an arbitrary filename, and we don't then need to use path-handling routines.
> 📌 Fix location to executable `.md` files in Thebe

- packages/site/src/components/Navigation/PrimarySidebar.tsx
- styles/toc.css
Closes https://github.com/jupyter-book/mystmd/issues/1672.
Here is what the changes look like in both light and dark mode for a Chromium-based browser:
No changes were needed for Firefox, hence the use of `-webkit-scrollbar` only.
> 🎨 Style scrollbar

- .changeset/silent-months-trade.md
- packages/jupyter/src/output.tsx
- packages/myst-to-react/src/code.tsx
- packages/site/src/components/ContentBlocks.tsx
Very very simple UI to get this feature possible:
I am reusing the Dropdown.
I am going to push this functionality over the line and then we can refine the UI.
Fixes #50
Fixes jupyter-book/mystmd#1108
> 🙈 Hide Content based on tags

- .changeset/fifty-bikes-poke.md
- packages/site/src/components/DocumentOutline.tsx
This also makes it a property of the component, allowing for customization in the future.
Based on feedback from @dellaert and conforming to JupyterBook.
> 📖 `In this Article` --> `Contents`

- .changeset/long-shirts-behave.md
- packages/site/src/components/Bibliography.tsx
Based on feedback from @dellaert
> 🙈 Change hiding long bibliography from 5 to 15

- .changeset/rich-parrots-explode.md
- packages/myst-to-react/src/grid.tsx
For a grid spec `a b c d`, the `a` column number introduces an `sm` breakpoint. This means that for `<sm`, the number of columns is undefined, and defaults to 1. 
I think that users (myself included) would prefer to have direct control over the number of columns at all screen sizes. We could look to increase the number of columns supported, but I think 4 is fine.
> 💈Use `main` as minimum grid column breakpoint

- .changeset/heavy-geese-flow.md
- packages/myst-to-react/src/hashLink.tsx
- packages/site/src/components/Footnotes.tsx
This simple PR adds a `[@media(hover:hover)]` modifier to the class-names for HashLink instances that use `hover`. The following components are affected:
- `Heading`
- `SolutionRenderer`
- `References`
- `Footnotes`
- `Abstract`
- `Bibliography`
- `Backmatter`
- `Keywords`
This PR was motivated by #513, but I think the same logic holds -- our mobile site should not lose interactivity. It does change the aesthetics, though:
<details><summary>Screenshots</summary>
</details> 
Forgive the HiDPI images -- I was already playing around with this PR on mobile.
> 👈 Disable `hover` modifier for mobile in `HashLink`

- .changeset/lovely-cherries-collect.md
- themes/article/app/components/Article.tsx
Follows up from https://github.com/jupyter-book/myst-theme/pull/519
> ✏️ Restore original `title` in `DocumentOutline` of article theme

- .changeset/silly-deers-trade.md
- packages/common/src/utils.ts
Image urls were failing if they were in a site/project `part` - this is because the links were not getting rewritten for the CDN. This PR adds those links to the rewrite function.
> 🔗 Update static links in parts in config

- .changeset/smart-drinks-explain.md
- packages/jupyter/src/block.tsx
- packages/myst-to-react/src/block.tsx
Fixes jupyter-book/mystmd#1886
> 🧱 Simplify Blocks (remove grid-system)

- README.md
- docs/package.json
- docs/stories/0-Introduction.stories.mdx
- docs/stories/2-Admonitions.stories.mdx
- docs/stories/2-Dropdown.stories.mdx
- packages/common/README.md
- packages/diagrams/README.md
- packages/frontmatter/README.md
- packages/icons/README.md
- packages/jupyter/CHANGELOG.md
- packages/jupyter/README.md
- packages/myst-demo/README.md
- packages/myst-to-react/README.md
- packages/providers/README.md
- packages/search-minisearch/README.md
- packages/search/README.md
- packages/site/README.md
- styles/CHANGELOG.md
- styles/package.json
- themes/article/.gitmodules
- themes/article/README.md
- themes/article/template.yml
- themes/book/README.md
This PR does some general cleanup to remove EB references where we now use JB, and to ensure that the links and badges are all up to date.
> 🧹 Clean up links to EB & unify READMEs for packages

- .changeset/itchy-pugs-teach.md
- packages/jupyter/src/hooks.ts
This fixes a bug in how outputs with multiple minified mime bundles (with path properties) were having their mime bundles properly fetched and rebuilt, resulting in some mimebundles being stripped.
This had a direct effect on holoviews (bokeh, plotly) which this PR fixes (related: #527)
This bug could have also been responsible for other unexpected behaviour where ever the multiple minified mimebundles are present.
> holoviews support: fix output path fetching

- .changeset/famous-wasps-bow.md
- .changeset/wild-ghosts-tease.md
- package-lock.json
- packages/frontmatter/package.json
- packages/frontmatter/src/LaunchButton.tsx
- themes/book/app/components/ArticlePage.tsx
This PR closes #507 by changing the launch button UI to detect the target. 
It is motivated by https://github.com/2i2c-org/infrastructure/issues/5348 in 2i2c's sprint planning.
This feature is intended to bring us closer to a time in which the distinction between JupyterHub and BinderHub becomes increasingly less relevant. 
There are some nuances encoded in this UX; we assume that the JupyterHub uses `nbgitpuller`. In future, we (2i2c) would like to unify the features of nbgitpuller and mybinder so that the language for addressing contents can be drawn closer together.
https://github.com/user-attachments/assets/623c7b09-573a-4442-8130-51883883dd1d
In future, this feature should probably use a reducer — the business logic already feels more complicated than I would like.
> 🚀 Add `awesomebar`-like UX to launch button

- .changeset/blue-seals-arrive.md
- .changeset/config.json
- package-lock.json
- packages/landing-pages/.eslintrc.cjs
- packages/landing-pages/README.md
- packages/landing-pages/package.json
- packages/landing-pages/src/BlockHeading.tsx
- packages/landing-pages/src/CenteredBlock.tsx
- packages/landing-pages/src/InvalidBlock.tsx
- packages/landing-pages/src/JustifiedBlock.tsx
- packages/landing-pages/src/LandingBlock.tsx
- packages/landing-pages/src/LogoCloudBlock.tsx
- packages/landing-pages/src/SplitImageBlock.tsx
- packages/landing-pages/src/UnknownBlock.tsx
- packages/landing-pages/src/index.ts
- packages/landing-pages/src/utils.ts
- packages/landing-pages/tsconfig.json
- packages/myst-to-react/src/hashLink.tsx
- packages/myst-to-react/src/heading.tsx
- styles/button.css
- styles/index.js
- themes/book/app/root.tsx
- themes/book/app/routes/_index.tsx
- themes/book/package.json
- themes/book/styles/app.css
This PR is an implementation of an MVP for _landing page_ blocks to the book theme. It is being driven by the Product and Services team at 2i2c, which is tracking the work under https://github.com/2i2c-org/infrastructure/issues/5482
The goal here is to allow _communities_ to opt-in to welcoming their audience on the home page. The design requirements for the landing page are therefore different to regular page routes. This PR follows some scoping work to figure out what a potential design might look like. The exploration process can be viewed by following the chain of issues in the 2i2c infrastructure issue above.
An example website with the proper metadata (and patched theme deployment) can be found at https://2i2c.org/cryocloud-landing-demo/.
- `split-image` — a hero heading with an …
> 🛫 Add landing page blocks to book theme

- .changeset/large-needles-end.md
- .changeset/rotten-mangos-rescue.md
- packages/myst-demo/src/index.tsx
- packages/myst-to-react/src/MyST.tsx
- packages/myst-to-react/src/basic.tsx
- themes/article/app/components/Article.tsx
- themes/book/app/components/ArticlePage.tsx
By imposing the constraint that `root` cannot have a `class` or `label`, we can eliminate the need to render a `div` for this element.
> 🌲 Add `root` renderer

- .github/workflows/deploy.yml
This PR adds a deployment workflow that uses a personal fine-grained GitHub token to push to `myst-templates`. It will expire in 365 days. I've already tested this with https://github.com/myst-templates/book-theme/commit/c4a0e5d80187e543ef3363ae725b2007aa9b3683
> 🖥️ Add deploy workflow to CI

- Makefile
This PR ensures that we don't accidentally commit old assets to our deployed themes when building locally. These directories are copied naively to the built artifact, so we need to clear them ahead of time.
> 🛠️ Delete theme's built assets before build

- .changeset/swift-beds-raise.md
- packages/landing-pages/src/CenteredBlock.tsx
- packages/landing-pages/src/JustifiedBlock.tsx
- packages/landing-pages/src/LogoCloudBlock.tsx
- packages/landing-pages/src/SplitImageBlock.tsx
> ➿ Enable flex-wrap in landing-page links

- packages/myst-to-react/src/cite.tsx
- styles/button.css
This PR follows up #521 to support buttons with citations. In the long run, I think we might want to replace these selectors with something more React driven, but this is a first pass.
> 🎓 Add support for `button` in `cite` nodes

- .changeset/quick-needles-judge.md
- packages/landing-pages/src/JustifiedBlock.tsx
- styles/app.css
- styles/landing-pages.css
Fixes #575 by switching to a CSS grid layout, rather than a set of flex boxes. This ensures that we can responsively move links _below_ the main body of the section, and prevent links from stealing _body_ width.
> 🖼️ Fix layout of `justified` landing blocks

- .changeset/rich-suits-sniff.md
- packages/frontmatter/src/FrontmatterBlock.tsx
Adds an edit button to pages that have GitHub repo information to edit the corresponding page on the site.
closes #326
> ✍️ Feat: add edit button

- themes/book/styles/grid-system.css
Remove a spurious comma that was left in the style file for book-theme.
> 🤏 Fix grid-system footer override syntax error

- .changeset/slimy-nights-fail.md
- packages/jupyter/src/controls/NotebookCellControls.tsx
- packages/myst-to-react/src/admonitions.tsx
- styles/jupyter.css
- Restructured the `jupyter.css` file to use Tailwind CSS
- Used the latter to apply different styles to the table depending on the theme, making it readable, fixing https://github.com/jupyter-book/mystmd/issues/1595
- Hovering over a row now highlights the entire row instead of just the header column of that row
- - Hovering over a table uses the same highlight color regardless of line parity within the [dark | light] theme
---
_Everything works on my end, but make sure to check everything carefully because this is my first PR within this repo; also, this is my first time using changesets so in case more details are necessary, do not hesitate to change something_
_(edit: thinking about it now, I would prefer the bullet points above to be appended to the changeset so that other people …
> Make Jupyter tables readable in dark theme

- .changeset/silver-jeans-wonder.md
- packages/site/src/components/Navigation/Navigation.tsx
- packages/site/src/components/Navigation/PrimarySidebar.tsx
- packages/site/src/components/Navigation/TopNav.tsx
Fixes these issues:
- fixes https://github.com/jupyter-book/myst-theme/issues/462
- fixes https://github.com/jupyter-book/myst-theme/issues/514
- fixes https://github.com/jupyter-book/myst-theme/issues/601
- Makes text styling consistent (text-medium) in primary nav to ensure parity with top nav 
Given what was discussed in #458 by @agoose77 and @stevejpurves:
> 1. Users have a ToC, and maybe have a nav. They want the primary sidebar to be visible at all times (either as a drawer, or fixed on the page). They want the burger menu to appear only when the sidebar behaves as a drawer.
> 2. Users don't have a ToC, and have a nav. They want to hide_toc so that the primary sidebar is not visible unless the primary nav needs to be folded into the sidebar. They want the burger menu to appear when …
> 🫣 Fix primary sidebar & header not showing navigation buttons correctly when ToC is hidden

- .changeset/great-buckets-hammer.md
- packages/myst-to-react/src/image.tsx
This PR updates the early-return case in the component for rendering `image` nodes such that it includes a class name.
Fixes #625
> ✍️ Fix missing class name for `image` renderer

- .changeset/calm-rules-rescue.md
- packages/myst-to-react/src/code.tsx
Fixes jupyter-book/mystmd#2145
@matthewfeickert this should fix things for the background, as well as the location of the copy-icon when you are scrolling.
Before:
After:
> ⌨️ Cell block overflow color and copy icon location

- .github/workflows/release.yml
This is just the label of the action, no real changes — there was a conversation about this a while ago!
> 🐛 Remove the misleading "Slack notification" in the release action

- template/server.js
The template by default will only serve on localhost unless a host is specified and passed through.
See jupyter-book/mystmd#2254
> 🔐 Improve security for localhost
