jupyter-book/myst-theme

.changeset/wet-glasses-flash.md
package-lock.json
packages/myst-to-react/src/basic.tsx
packages/myst-to-react/src/heading.tsx
packages/myst-to-react/src/math.tsx

See https://github.com/executablebooks/mystjs/issues/120

🔗 HashLinks are now inside of margins

---

.changeset/gold-nails-boil.md
packages/frontmatter/src/FrontmatterBlock.tsx

🐛 Alignment of OpenAccessBadge

---

.changeset/flat-rules-heal.md
packages/myst-to-react/src/crossReference.tsx

See executablebooks/mystjs#225

🐛 Use urlbase for cross-reference links

---

.changeset/five-fans-sell.md
packages/site/src/components/DocumentOutline.tsx

See executablebooks/myst-book-theme#2
Thanks @thesamovar.

👩🏻‍🎨 Improve the document outline

---

.changeset/shaggy-items-tap.md
docs/stories/2-Admonitions.stories.mdx
packages/myst-to-react/src/admonitions.tsx
packages/myst-to-react/src/reactive.tsx

✅ Simple admonitions and hide icons

---

packages/site/src/components/Navigation/TableOfContents.tsx

Some small improvements to spacing, nothing major.
Looking forward to doing more of a push on the TOC soon!!

🏗 Put the toc in the margin

---

.changeset/tidy-walls-talk.md
packages/site/src/components/Navigation/TableOfContents.tsx

This was broken with some of the recent column updates!

🧭 Update mobile navigation

---

.changeset/proud-yaks-applaud.md
packages/myst-to-react/src/heading.tsx

See executablebooks/jupyterlab-myst#90

¶ Change to pilcrow marker

---

.changeset/honest-cameras-joke.md
.changeset/proud-months-refuse.md
styles/app.css
styles/typography.css

Fixes a few things related to Jupyter and inline styles

👩🏻‍🎨 Update styles

---

.changeset/cyan-paws-hear.md
packages/myst-to-react/src/iframe.tsx

@lwasser - I noticed that the iframe tutorial was broken on our call, this fixes it -- it had zero height! Still on my list to get you some onboarding pointers, but it is probably helpful if you can actually see the videos ... 📺

📺 Iframe height should be fixed to more than zero

---

.changeset/weak-lamps-give.md
packages/myst-demo/src/index.tsx

This should resolve https://github.com/executablebooks/mystjs/issues/261

🚨 Display tex warnings in myst-demo

---

.changeset/hot-spies-cheat.md
packages/site/src/components/Navigation/TableOfContents.tsx

See executablebooks/mystjs#276 and #25

🐛 Fix navigation on smaller screens

---

.changeset/new-snails-explain.md
packages/myst-to-react/src/admonitions.tsx
packages/myst-to-react/src/dropdown.tsx

👻 Fix shadows on hover for dropdown/callouts

---

.changeset/honest-spoons-visit.md
packages/frontmatter/src/downloads.tsx
packages/frontmatter/src/licenses.tsx
packages/myst-demo/src/index.tsx
packages/myst-to-react/src/admonitions.tsx
packages/myst-to-react/src/components/CopyIcon.tsx
packages/myst-to-react/src/components/LinkCard.tsx
packages/myst-to-react/src/crossReference.tsx
packages/myst-to-react/src/dropdown.tsx
packages/myst-to-react/src/inlineError.tsx
packages/myst-to-react/src/links/github.tsx
packages/myst-to-react/src/links/index.tsx
packages/myst-to-react/src/links/rrid.tsx
packages/myst-to-react/src/links/wiki.tsx
packages/myst-to-react/src/math.tsx
packages/site/src/components/FooterLinksBlock.tsx
packages/site/src/components/Navigation/ThemeButton.tsx
packages/site/src/components/Navigation/TopNav.tsx

This improves the performance of heroicons for remix, previously we were shipping all heroicons in the bundled code.

🌲 Treeshake heroicons

---

.changeset/orange-pants-destroy.md
packages/site/src/components/Navigation/ThemeButton.tsx
packages/site/src/components/Navigation/TopNav.tsx

Some subtle changes that give it a more modern feel out the door.
TODO:
- fix logo text color
- fix logo background

✨ Turn the TopNav white

---

.changeset/chatty-emus-watch.md
.changeset/dirty-goats-report.md
.changeset/pink-zoos-dress.md
packages/icons/src/myst.tsx
packages/site/src/components/DocumentOutline.tsx
packages/site/src/components/Navigation/TableOfContents.tsx
packages/site/src/components/Navigation/TopNav.tsx
styles/index.js

And corrected the color of the nav menu:

🎨 Improvements to nav and toc

---

.changeset/healthy-birds-itch.md
packages/myst-to-react/src/index.tsx
packages/myst-to-react/src/inlineExpression.tsx

- https://github.com/executablebooks/mystjs/pull/368

🧮 Inline user_expressions

---

packages/jupyter/src/jupyter.tsx

See #59.
@stevejpurves this is a minimal fix ported from yours. I think it is worth getting in and then rebasing your wider refactor on top?

🐛 Minimal fix for cross-ref recursion

---

.changeset/metal-insects-breathe.md
.changeset/shiny-kiwis-serve.md
packages/frontmatter/src/FrontmatterBlock.tsx

@tavin this should help out! Thanks again fro catching this. :)

💅 Improve the frontmatter spacing

---

.changeset/few-adults-decide.md
styles/block-styles.css
styles/index.js

See executablebooks/mystjs#213

🌃 Add a framed style for images

---

.changeset/thin-scissors-taste.md
packages/myst-to-react/src/basic.tsx
packages/myst-to-react/src/card.tsx
packages/myst-to-react/src/grid.tsx
packages/myst-to-react/src/tabs.tsx
styles/app.css
styles/grid.css
styles/typography.css

🎨 Updates for margins

---

.changeset/cold-schools-drive.md
.changeset/tidy-balloons-do.md
packages/myst-to-react/src/cite.tsx
packages/myst-to-react/src/crossReference.tsx
packages/myst-to-react/src/footnotes.tsx
packages/myst-to-react/src/links/github.tsx
packages/myst-to-react/src/links/index.tsx
packages/myst-to-react/src/links/rrid.tsx
styles/hover.css

- See https://github.com/executablebooks/mystjs/pull/389

🔗 Add support for github issue previews

---

README.md

@stevejpurves added a few docs for when I am away next week!

📖 Add docs on deployment

---

.changeset/tasty-cobras-thank.md
packages/myst-to-react/src/math.tsx

🐛 Fix single line formula scrollbar issue

---

.changeset/curvy-students-march.md
packages/myst-to-react/src/exercise.tsx
packages/myst-to-react/src/index.tsx

🧑🏼‍🏫 Add sphinx exercise initial implementation

---

.changeset/great-comics-marry.md
packages/jupyter/src/output.tsx

🐛 Remove hooks from NodeRenderer

---

.changeset/honest-worms-sell.md
packages/myst-to-react/src/exercise.tsx
packages/myst-to-react/src/index.tsx
packages/myst-to-react/src/unknown.tsx

This adds an unknown directive that improves rendering.
See also:
- https://github.com/executablebooks/jupyterlab-myst/issues/143
- https://github.com/executablebooks/mystjs/pull/403

🙀 Unknown directives have better rendering

---

.changeset/kind-forks-tie.md
.changeset/small-toes-greet.md
packages/myst-to-react/src/basic.tsx
packages/myst-to-react/src/components/HoverPopover.tsx
packages/myst-to-react/src/crossReference.tsx
packages/providers/src/xref.tsx

- also supports definition lists
- Fixes a remote-page bug for rendering the cross reference
- Improves performance to only lookup references when they are hovered, rather than on page load.

🔗 Improve cross-references for remote pages

---

.changeset/twenty-kings-beam.md
packages/jupyter/src/jupyter.tsx
packages/jupyter/src/output.tsx
packages/jupyter/src/providers.tsx
packages/site/src/components/EnableCompute.tsx

- fixed missing outputs on first render
- big simplification of the ref management for cells,  removed unneeded complexity

🪐 Thebe: fix/missing outputs on page load

---

docs/stories/0-Introduction.stories.mdx
packages/icons/src/myst.tsx
packages/myst-demo/README.md

See executablebooks/team-compass#21

🎨 Rebrand to mystmd.org

---

.changeset/large-geese-sparkle.md
.changeset/lovely-cups-juggle.md
.changeset/serious-weeks-thank.md
packages/myst-demo/src/index.tsx
packages/myst-to-react/src/extensions/chemicalFormula.tsx
themes/book/app/utils/loaders.server.ts

This now respects `Ca+` adds an aria-description and changes to a span, rather than code.

🧑🏻‍🔬 Slight improvements to chemical formulas

---

Makefile

otherwise you get a poor commit message which is auto pushed

👮🏻check for jq before commiting

---

.changeset/nice-clocks-wash.md
packages/site/src/components/Navigation/TopNav.tsx
packages/site/src/loaders/utils.ts
themes/article/template.yml
themes/book/template.yml

This PR stems from the conversation in [mystjs #155](https://github.com/executablebooks/mystjs/issues/155).

🎨 Add template option for logo in dark mode

---

packages/jupyter/src/ConnectionStatusTray.tsx
packages/jupyter/src/index.tsx
packages/jupyter/src/output.tsx
packages/site/src/components/EnableCompute.tsx
packages/site/src/pages/Article.tsx

Improvements to UI feedback from the `thebe` events mechanism, mainly to provide better feedback during longer binder connections and when using jupyterlite.

 🪧 UI Feedback on Jupyter Status

---

.changeset/few-bottles-act.md
packages/jupyter/src/execute/hooks.ts
packages/jupyter/src/execute/leaf.tsx
packages/jupyter/src/execute/reducer.ts
packages/jupyter/src/execute/selectors.ts

Some largely defensive changes to address the immedate cause of the error in issue #158 and to try and allow for certain fields in the mdast not to be defined.

some changes to address #158 

---

.changeset/pretty-houses-turn.md
package-lock.json
packages/jupyter/package.json
packages/jupyter/src/execute/hooks.ts
packages/jupyter/src/execute/selectors.ts
packages/jupyter/src/execute/utils.ts
packages/site/package.json

This now properly accounts for markdown cells and code cells and only sets busy state for code cells.

🪐 Fix busy state in Thebe

---

packages/myst-to-react/src/iframe.tsx

This allows for figure iframes with captions.
See executablebooks/mystmd#483

📺 Improve Iframe node padding

---

.changeset/chilly-mangos-type.md
package-lock.json
package.json
packages/jupyter/package.json
packages/site/src/components/DocumentOutline.tsx
packages/site/src/pages/Article.tsx
themes/article/app/routes/$.tsx
themes/article/template.yml
themes/book/app/routes/$.tsx
themes/book/template.yml

* adds site level `hide_toc`,`hide_outline` and `hide_footer_links` to book theme
* renamed `hide_footer` to `hide_footer_links` in article theme

🙈 Hide outline and footer links

---

.changeset/breezy-icons-kneel.md
packages/jupyter/src/output.tsx

@kolibril13 this is something that you mentioned, this should improve it slightly!
I am also moving figure --> div as many times outputs are not "figures".

🔭 Add space under jupyter outputs

---

.changeset/eighty-ducks-retire.md
packages/site/src/pages/Article.tsx
themes/book/app/routes/$.tsx

📃 Show abstract in book theme

---

.changeset/cuddly-buses-cry.md
.changeset/silver-rules-sin.md
.changeset/tender-adults-vanish.md
docs/stories/1-GridSystem.stories.mdx
packages/providers/src/grid.tsx
packages/providers/src/index.tsx
packages/providers/src/theme.tsx
packages/site/src/components/Bibliography.tsx
packages/site/src/components/ContentBlocks.tsx
packages/site/src/components/Headers.tsx
packages/site/src/components/Navigation/TableOfContents.tsx
packages/site/src/components/index.ts
packages/site/src/pages/Root.tsx
styles/grid-system.css
styles/index.js
themes/article/app/routes/$.tsx
themes/book/app/routes/$.tsx

This adds the ability to change the grid system in other themes.
Ensure that children components are using the correct grid.

🧩 Grid system improvements

---

.changeset/lazy-crabs-walk.md
.changeset/tiny-ghosts-notice.md
packages/jupyter/src/embed.tsx
packages/jupyter/src/output.tsx
packages/jupyter/src/safe.tsx

See https://github.com/orgs/executablebooks/discussions/1062#discussioncomment-6682400

🐛 Guard outputs and fix embed children

---

.changeset/nasty-comics-relate.md
package-lock.json
packages/jupyter/package.json
packages/site/package.json

Fixes `ipywidgets` issue in earlier `pyodide-kernels`.
https://github.com/executablebooks/thebe/issues/672

👊🏽 bump `thebe-lite`

---

.changeset/proud-pants-cross.md
packages/site/src/components/Headers.tsx

This increases the margin, and improves the alignment. It also changes the structure so as not to interfere with z-index (and future author/affiliation buttons).
cc @eurunuela

🌄 Improvements to article header

---

.changeset/rare-pillows-float.md
themes/article/app/routes/$.tsx

⬇️ Add downloads to article theme

---

packages/site/src/components/Navigation/Navigation.tsx
themes/book/app/routes/$.tsx

⌨️ fixing tab ordering for TOC

---

.changeset/nasty-cars-battle.md
packages/myst-to-react/src/code.tsx

🏷 Add filename to code block

---

.changeset/fast-onions-thank.md
packages/site/src/components/SkipToArticle.tsx

Minor typos and remove blur (which isn't needed after an explicit focus).

⌨️ Simplifications to the skip-to-content handler

---

.changeset/orange-papayas-chew.md
package-lock.json
package.json
packages/common/.eslintrc.cjs
packages/myst-to-react/package.json
packages/site/package.json

I think ? I'm not a Js person, but I have the impression this is needed.

Add missing dependency for myst-to-react

---

packages/myst-to-react/src/basic.tsx
styles/app.css
styles/proof.css

Related to: https://github.com/executablebooks/mystmd/pull/694

〰 Add line for algorithms

---

.changeset/fifty-bears-guess.md
packages/myst-to-react/src/basic.tsx
packages/myst-to-react/src/cite.tsx

- Add `<span>` as a known element type

🎨 Fix citation link styles

---

.changeset/violet-flies-marry.md
packages/myst-to-react/src/exercise.tsx

🐭🐘 - Ensure size of SVG icons with no classes

---

packages/myst-to-react/src/basic.tsx

🐛 Fix react warning on key errors for text

---

.changeset/empty-jobs-notice.md
packages/myst-to-react/src/basic.tsx

See executablebooks/mystmd#749

🎨 Add basic div/span functionality to renderer

---

.changeset/strong-masks-cry.md
packages/jupyter/src/figure.tsx
packages/myst-to-react/src/basic.tsx
styles/figures.css

See executablebooks/mystmd#770

🌉 Minor improvements for handling subfigures

---

.changeset/angry-wolves-obey.md
.changeset/six-trees-rule.md
package-lock.json
packages/jupyter/package.json
packages/jupyter/src/controls/ArticleCellControls.tsx
packages/jupyter/src/controls/Buttons.tsx
packages/jupyter/src/controls/NotebookToolbar.tsx
packages/jupyter/src/execute/provider.tsx
packages/jupyter/src/providers.tsx
packages/providers/src/index.tsx
packages/providers/src/project.tsx
packages/site/package.json
packages/site/src/pages/Article.tsx
packages/site/src/pages/Root.tsx
themes/article/.gitignore
themes/book/.gitignore

update thebe to the latest version, which in turn updates the latest jupyterlite and jupyterlab dependencies.
There are large lockfile changes here mainly due to the thebe dependencies. Thebe core and lite are dynamically loaded but thebe-react still brings in these dependencies.

🆙 update thebe

---

packages/myst-to-react/docs/index.md
packages/myst-to-react/src/MyST.tsx

My attempt at trying to fix #294 and write some docs.
I'm still figuring out JS/TS, so this is untested as I don't know yet how to use a dev version locally.

Make Default MyST to act renderer configurable

---

.changeset/brown-foxes-drop.md
packages/frontmatter/src/FrontmatterBlock.tsx
packages/site/src/components/Headers.tsx

@stevejpurves reported a bug in safari.

🎨 Fix frontmatter in safari

---

.changeset/clean-cows-boil.md
package-lock.json
packages/jupyter/package.json
packages/site/package.json

This upgrade will fix saved session issues for binder build urls containing hashes and query params

👊🏽 bump thebe

---

.changeset/tasty-lemons-switch.md
packages/site/src/components/Headers.tsx

🎨 Add `flex-grow` for article header

---

.changeset/wise-lizards-cheat.md
packages/frontmatter/src/FrontmatterBlock.tsx

See executablebooks/mystmd#607

📆 Show date as UTC date

---

.changeset/purple-hornets-yawn.md
packages/myst-to-react/src/code.tsx

This can happin in LaTeX in a `texttt` context.

👨🏻‍💻 Allow inline code to have children

---

.changeset/mean-cycles-push.md
packages/myst-to-react/src/admonitions.tsx

Fixes executablebooks/jupyterlab-myst#201 by exposing classname to DOM.

🎨 Write class name to admonition

---

.changeset/old-penguins-call.md
package-lock.json
packages/jupyter/package.json
packages/site/package.json

fixes https://github.com/executablebooks/thebe/issues/737 in the `myst-theme`

👊🏽 `thebe-*`

---

README.md

Adds a few links to the theme documentation in the README, in the hopes that this makes them easier to discover.

📖  Add links to the MyST Theme documentation

---

.changeset/early-nails-act.md
packages/myst-to-react/src/basic.tsx

This PR adds a React renderer for `aside` nodes.
Closes #327

🖌 Add support for `aside` directive

---

.changeset/poor-flies-notice.md
packages/frontmatter/src/AuthorPopover.tsx

🛟 lift author popover to z-10

---

.changeset/grumpy-crews-sneeze.md
packages/frontmatter/src/downloads.tsx
packages/site/src/pages/Article.tsx
themes/article/app/components/ArticlePage.tsx
themes/article/app/components/Downloads.tsx

See https://github.com/executablebooks/myst-theme/issues/352

📑 Downloads combined with project

---

.changeset/quick-kiwis-behave.md
packages/myst-to-react/src/basic.tsx

🐛 Remove blank space around included content

---

.changeset/chatty-trees-repair.md
packages/myst-to-react/src/cite.tsx
packages/site/src/index.ts
packages/site/src/themeCSS.ts
styles/citations.css
themes/article/app/components/ArticlePage.tsx
themes/article/app/root.tsx
themes/article/app/routes/myst-theme[.css].ts
themes/article/template.yml
themes/book/app/root.tsx
themes/book/app/routes/$.tsx
themes/book/app/routes/myst-theme[.css].ts
themes/book/template.yml

This allows for an option of `numbered_references` in the `site.options`.

🔢 Support numbered references

---

.changeset/clean-ways-compete.md
packages/site/src/components/Navigation/TableOfContentsItems.tsx
styles/hover.css
styles/index.js

♿️ Small accessibility improvements

---

.changeset/red-sheep-peel.md
packages/site/src/components/Navigation/TopNav.tsx

See executablebooks/mystmd#1178

🐛 `useNavLinkProvider` in top navigation

---

.changeset/famous-nails-suffer.md
.changeset/small-papayas-divide.md
packages/myst-to-react/src/crossReference.tsx
packages/providers/src/xref.tsx

🧭 Recursive, external cross references

---

.changeset/poor-laws-help.md
docs/stories/1-GridSystem.stories.mdx
styles/grid-system.css
styles/index.js

⚖️ a centered grid

---

packages/site/src/components/index.ts

#416 actually broke the themes build, this is a hot fix 😅

🔥🔧 fix missing export

---

.changeset/afraid-plants-kiss.md
themes/article/app/components/Article.tsx
themes/book/app/components/ArticlePage.tsx

@rowanc1 brought this to my attention somewhere.

:wrench: Fix positioning of secondary sidebar when scrolling

---

.changeset/brown-chairs-clean.md
docs/stories/1-GridSystem.stories.mdx
styles/grid-system.css
styles/index.js

fixes a issue with the grid and makes spacing better 🤩

🔧 fix lg breakpoint for center-grid

---

.changeset/flat-roses-sit.md
styles/grid-system.css

🔥🔧 fixes outline grid position at `lg`

---

README.md

executablebooks -> jupyter-book

docs: update origin in links for GitHub Org change

---

.changeset/two-hotels-own.md
packages/myst-to-react/src/admonitions.tsx

Fixes jupyter-book/mystmd#1319

🗃 Start admonitions in the open position

---

.changeset/new-pens-thank.md
themes/article/app/root.tsx
themes/book/app/root.tsx

Fixes https://github.com/jupyter-book/mystmd/issues/1449

🌠 Support favicon in static builds

---

.changeset/breezy-cups-kick.md
packages/site/src/components/Navigation/Search.tsx

↔️ Truncate long results

---

.changeset/calm-panthers-play.md
styles/button.css

〰️ Remove underline from `a.button`

---

.changeset/famous-wasps-bow.md
packages/frontmatter/src/LaunchButton.tsx

Closes #511 as part of 2i2c's work on https://github.com/2i2c-org/infrastructure/issues/5045

ℹ️ Add note about JupyterHub requirements to launch bar

---

.changeset/red-toys-repeat.md
packages/landing-pages/src/LandingBlock.tsx

🎩 Fix landing-page block class lookup

---

.changeset/angry-beans-exercise.md
.changeset/five-steaks-argue.md
packages/site/src/pages/Root.tsx
themes/article/app/root.tsx
themes/book/app/root.tsx

🐛 Ensure CSS has baseURL directly

---

themes/book/template.yml

✏️ Fix metadata for template URL

---

flake.lock
flake.nix

For contributors to MyST, the dev flakes make it easier to get started. I take fully responsibility for this, and we don't promise to maintain it anywhere.

❄️ Add nix dev-shell flake

---

README.md

Fixes references to `--submodules`

📜 Drop submodule references in contributing

---

.changeset/honest-months-glow.md
packages/frontmatter/src/Authors.tsx

This PR abstracts away the social-icon handling to prepare for easier extension with new social icons.

💬 Refactor social media icons rendering

---

.changeset/nasty-adults-fetch.md
packages/site/src/components/Navigation/HomeLink.tsx
packages/site/src/components/Navigation/TopNav.tsx
themes/article/template.yml
themes/book/template.yml

🔗 Allow specifying custom URL for navigation bar logo

---

Makefile
docs/examples.md
docs/requirements.txt

This demonstrates that bokeh plots work with this theme.
- closes #527

Add bokeh example

---

README.md
docs/stories/1-GridSystem.stories.mdx

I believe the reference to mystjs/docs is a leftover from past times

the mystmd repo has changed place, and one typo

---

.changeset/cool-grapes-decide.md
packages/site/src/components/Navigation/TableOfContentsItems.tsx

Fix static html sidebar nav menu collapse bug (#635)

:beetle: :boom: Fix static html sidebar nav menu collapse bug

---

.changeset/tidy-baboons-eat.md
docs/myst.yml
packages/site/src/components/Navigation/TopNav.tsx

Fixes jupyter-book/mystmd#1531. Related to jupyter-book/mystmd#1449 and similar to #475.

Add missing base URLs in top navigation
